version: "3.3"
services:
#  frontend:
#    stdin_open: true
#    build:
#      context: ./frontend
#    ports:
#      - "3000:3000"
#    volumes:
#      - "./app/node_modules"
#      - "./frontend/:/app"

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - "/usr/app/node_modules"
      - "./backend/:/usr/app/"
