version: "3.3"
services:
  frontend:
    stdin_open: true
    build:
      context: ./frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    links:
      - mongo
    environment:
      - URL_MONGO=mongodb://root:password@mongo
   
  mongo:
    container_name: database
    image: mongo:4.0
    volumes:
      - "mongodb_data_container:/data/db"
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongodb_data_container: